In [1]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
import numpy as np

In [5]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros(3,3)

TypeError: data type not understood

In [8]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
type(1)

int

In [10]:
type(1.0)

float

In [11]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(10,2)

array([[0.21048749, 0.17084967],
       [0.02385557, 0.50834501],
       [0.28203286, 0.17294775],
       [0.77201256, 0.58964024],
       [0.83148292, 0.7131117 ],
       [0.43178013, 0.06128467],
       [0.83562942, 0.69419714],
       [0.61942135, 0.49363485],
       [0.54540438, 0.20038297],
       [0.51714013, 0.29220152]])

In [17]:
np.random.randn(5,4)

array([[ 0.59034931, -0.37516055,  1.86437091, -0.4183356 ],
       [-2.66877002, -0.22932462,  0.27115606,  0.05185809],
       [ 0.31276054,  0.55323457, -1.43057254,  2.55058363],
       [-0.18770775,  1.96051067,  0.99067301,  1.23366517],
       [-1.20287364, -1.07280498,  1.5038545 ,  0.28032011]])

In [20]:
np.random.randint(1,10,10)

array([4, 9, 6, 1, 2, 4, 3, 5, 7, 5])

In [21]:
arr = np.arange(25)

In [22]:
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([16, 22, 35,  4, 18, 47, 12, 16,  2, 45])

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [30]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [31]:
arr.dtype

dtype('int32')

In [32]:
ranarr

array([16, 22, 35,  4, 18, 47, 12, 16,  2, 45])

In [33]:
ranarr.argmax

<function ndarray.argmax>

In [34]:
ranarr.argmax()

5

In [35]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [36]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr = np.arange(0,10)

In [39]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr/arr

c:\users\citdbs\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
1/arr

c:\users\citdbs\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[8]

8

In [47]:
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[0:5] = 100

In [51]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr = arr[0:6]

In [55]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [56]:
slice_of_arr[:] = 99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy = arr.copy()

In [60]:
arr_copy[:] = 200

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
# mat[row,col]

In [63]:
# mat[row][col]

In [64]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [65]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
mat[0]

array([ 5, 10, 15])

In [67]:
mat[2]

array([35, 40, 45])

In [68]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
mat[1][0]

20

In [70]:
mat[1,0]

20

In [71]:
mat[0,2]

15

In [72]:
mat[:2,]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
mat[:2,1]

array([10, 25])

In [74]:
mat[:2,:1]

array([[ 5],
       [20]])

In [75]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [77]:
arr = np.arange(1,11)

In [78]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
bool_arr = arr > 4

In [80]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])